# 질문 정규화 규칙 설정 파일
# LLM 검색 시스템의 임베딩 전 질문 정제 규칙

# ============================================================
# 1. 기본 설정
# ============================================================
normalization:
  enabled: true                    # 정규화 활성화 여부
  log_level: "INFO"               # 로그 레벨 (DEBUG, INFO, WARNING, ERROR)
  fallback_on_error: true         # 오류 시 원본 반환 여부

# ============================================================
# 2. 문장 분리 설정 (kss)
# ============================================================
sentence_splitting:
  enabled: true                    # 문장 분리 활성화
  use_kss: true                   # kss 라이브러리 사용 여부
  min_sentence_length: 5          # 최소 문장 길이 (문자 수)
  max_sentences: 10               # 최대 문장 수 (초과 시 잘림)

# ============================================================
# 3. 형태소 분석 설정 (Kiwi)
# ============================================================
morphological_analysis:
  enabled: true                    # 형태소 분석 활성화
  use_kiwi: true                  # Kiwi 라이브러리 사용 여부
  
  # 추출할 품사 태그
  target_pos_tags:
    - NNG                          # 일반 명사
    - NNP                          # 고유 명사
    - VV                           # 동사
    - VA                           # 형용사
    - MAG                          # 일반 부사
    - NNB                          # 의존 명사
    - VX                           # 보조 용언
  
  # 필터링 규칙
  filtering:
    min_token_length: 2           # 최소 토큰 길이
    remove_numbers: false         # 숫자 제거 여부
    remove_single_chars: true     # 단일 문자 제거

# ============================================================
# 4. 불용어 설정
# ============================================================
stopwords:
  enabled: true                    # 불용어 제거 활성화
  
  # 조사
  particles:
    - 이
    - 가
    - 을
    - 를
    - 은
    - 는
    - 에
    - 의
    - 로
    - 으로
    - 와
    - 과
    - 도
    - 만
    - 부터
    - 까지
    - 에게
    - 에서
    - 께
    - 께서
    - 한테
  
  # 어미
  endings:
    - 입니다
    - 습니다
    - 했습니다
    - 있습니다
    - 없습니다
    - 합니다
    - 됩니다
    - 이다
    - 하다
    - 되다
  
  # 대명사
  pronouns:
    - 그
    - 이
    - 저
    - 그것
    - 이것
    - 저것
    - 여기
    - 거기
    - 저기
  
  # 기타 불용어
  others:
    - 것
    - 수
    - 때
    - 곳
    - 말
    - 등
    - 및

# ============================================================
# 5. 텍스트 정제 규칙
# ============================================================
text_cleaning:
  enabled: true
  
  # 공백 처리
  whitespace:
    normalize: true               # 연속 공백을 하나로
    trim: true                    # 앞뒤 공백 제거
  
  # 특수문자 처리
  special_chars:
    remove_pattern: "[^\\w\\s가-힣.,!?;:\\-]"  # 제거할 특수문자 패턴
    keep_punctuation: true        # 문장부호 유지 여부
    punctuation_list:
      - "."
      - ","
      - "!"
      - "?"
      - ";"
      - ":"
  
  # 줄바꿈 처리
  newlines:
    replace_with_space: true      # 줄바꿈을 공백으로 대체
  
  # 반복 문자 처리
  repeated_chars:
    enabled: true                 # 반복 문자 정규화
    max_repetition: 2             # 최대 반복 횟수 (예: "ㅋㅋㅋㅋ" → "ㅋㅋ")

# ============================================================
# 6. 동의어/유사어 처리 (Optional)
# ============================================================
synonyms:
  enabled: false                   # 동의어 치환 활성화
  
  # 동의어 매핑 (key → value로 치환)
  mappings:
    "휴가": "연차"
    "월급": "급여"
    "회사": "기업"

# ============================================================
# 7. 질문 패턴 정규화 (Optional)
# ============================================================
question_patterns:
  enabled: false                   # 질문 패턴 정규화
  
  # 질문 유형별 키워드 추출
  what_patterns:
    - "무엇"
    - "뭐"
    - "어떤"
  
  how_patterns:
    - "어떻게"
    - "방법"
    - "절차"
  
  when_patterns:
    - "언제"
    - "시기"
    - "기간"
  
  where_patterns:
    - "어디"
    - "장소"

# ============================================================
# 8. 성능 최적화
# ============================================================
performance:
  cache_enabled: true             # 결과 캐싱 활성화
  cache_size: 1000                # 캐시 최대 크기
  timeout_seconds: 10             # 처리 타임아웃 (초)

# ============================================================
# 9. 디버깅 설정
# ============================================================
debug:
  log_original_query: true        # 원본 쿼리 로깅
  log_intermediate_steps: true    # 중간 단계 로깅
  log_final_result: true          # 최종 결과 로깅
  compare_before_after: true      # 전/후 비교 로깅

